### ISSUE TITLE
'mongodump' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Mohit8982** [theouerd/mongodb-autoBackup#1]
i am facing this problem any idea?

**Comment by theouerd** [comment]
Did you set your environment variables ?

**Comment by theouerd** [comment]
Did you set your environment variables ?

Check the link bellow for more details : 
https://stackoverflow.com/a/15055641/10558153

**Comment by orendavisdev** [comment]
@Mohit8982 you are probably trying to run the app on a machine where mongo is not installed locally.
